yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: node-modules

packageExtensions:
  '@oclif/config@*':
    dependencies:
      'lodash': '*'
      '@oclif/plugin-help': '*'
      '@oclif/plugin-plugins': '*'
      '@oclif/plugin-not-found': '*'
      '@oclif/plugin-autocomplete': '*'
  '@oclif/command@*':
    dependencies:
      'cli-ux': '*'
      'chalk': '*'
